### ISSUE TITLE
Driver not able to accept/reject travel participation.

### ISSUE THREAD

**Issue by nawaz2013** [smartcommunitylab/sco.carpooling#15]
STEPS
- offered a travel on Jan 27 using user Id for e.g. using userId  '53'.  (see [1])
- create a participation request for e.g. using userId '52' (see booking array in [1])
- driver receive notification but is unable to accept/reject request. (see [2])

[1]

{
    "_id" : ObjectId("568b8dace4b034633b821fae"),
    "_class" : "it.smartcommunitylab.carpooling.model.Travel",
    "from" : {
        "name" : "Parcheggio Studenti, Via Mesiano, Trento",
        "address" : "Parcheggio Studenti, Via Mesiano, Trento",
        "latitude" : 46.065354,
        "longitude" : 11.140242,
        "range" : 1,
        "coordinates" : [ 
            46.065354, 
            11.140242
        ]
    },
    "to" : {
        "name" : "Via Giuseppe Missori, Verona",
        "address" : "Via Giuseppe Missori, Verona",
        "latitude" : 45.450369,
        "longitude" : 10.985596,
        "range" : 1,
        "coordinates" : [ 
            45.450369, 
            10.985596
        ]
    },
    "when" : NumberLong(1453887240000),
    "route" : {
        "from" : {
            "name" : "parking aisle",
            "stopId" : {
                "_id" : "",
                "agencyId" : ""
            },
            "lon" : "11.140338121521076",
            "lat" : "46.06535867118184"
        },
        "to" : {
            "name" : "corner of Via Giuseppe Missori and Via Angelo Butturini",
            "stopId" : {
                "_id" : "",
                "agencyId" : ""
            },
            "lon" : "10.985596",
            "lat" : "45.450369"
        },
        "startime" : NumberLong(1453887240000),
        "endtime" : NumberLong(1453893291000),
        "duration" : NumberLong(6051000),
        "walkingDuration" : NumberLong(6051),
        "leg" : [ 
            {
                "legId" : "null_null",
                "startime" : NumberLong(1453887240000),
                "endtime" : NumberLong(1453893291000),
                "duration" : NumberLong(6051),
                "from" : {
                    "name" : "parking aisle",
                    "lon" : "11.140338121521076",
                    "lat" : "46.06535867118184"
                },
                "to" : {
                    "name" : "corner of Via Giuseppe Missori and Via Angelo Butturini",
                    "lon" : "10.985596",
                    "lat" : "45.450369"
                },
                "transport" : {
                    "type" : "CAR"
                },
                ...
    "userId" : "53",
    "places" : 4,
    "intermediateStops" : false,
    "bookings" : [ 
        {
            "traveller" : {
                "_id" : "52"
            },
            "recurrent" : false,
            "date" : ISODate("2016-01-27T09:34:00.000Z"),
            "accepted" : 0
        }
    ],
    "active" : true,
    "communityIds" : [ 
        "cPCommunity1", 
        "cPCommunity2"
    ]
}

[2]

![accept-reject2](https://cloud.githubusercontent.com/assets/4034293/12112128/ce19c6da-b39a-11e5-9a53-d82ba50b569e.png)

![accept-reject1](https://cloud.githubusercontent.com/assets/4034293/12112131/d291ce42-b39a-11e5-9751-97e473159e10.png)

**Comment by nj** [comment]
Please remember to wrap code - like in the case of the JSON - within a [code block](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).

Without you are spamming quite many people (24+), due to the `@` is normally used for tagging/notifying related people when writing as regular text (non-code).

**Comment by nawaz2013** [comment]
My bad..
Please excuse me for the inconvenience caused.
I have removed the @ from comment.

**Comment by nj** [comment]
No worries, but as you can see, wrapping the code - either with or without syntax highlightning - will make the display better and easier to overview:

``` json
{
"_id" : ObjectId("568b8dace4b034633b821fae"),
"_class" : "it.smartcommunitylab.carpooling.model.Travel",
"from" : {
"name" : "Parcheggio Studenti, Via Mesiano, Trento",
"address" : "Parcheggio Studenti, Via Mesiano, Trento",
"latitude" : 46.065354,
"longitude" : 11.140242,
"range" : 1,
"coordinates" : [
46.065354,
11.140242
]
},
"to" : {
"name" : "Via Giuseppe Missori, Verona",
"address" : "Via Giuseppe Missori, Verona",
"latitude" : 45.450369,
"longitude" : 10.985596,
"range" : 1,
"coordinates" : [
45.450369,
10.985596
]
},
"when" : NumberLong(1453887240000),
"route" : {
"from" : {
"name" : "parking aisle",
"stopId" : {
"_id" : "",
"agencyId" : ""
},
"lon" : "11.140338121521076",
"lat" : "46.06535867118184"
},
"to" : {
"name" : "corner of Via Giuseppe Missori and Via Angelo Butturini",
"stopId" : {
"_id" : "",
"agencyId" : ""
},
"lon" : "10.985596",
"lat" : "45.450369"
},
"startime" : NumberLong(1453887240000),
"endtime" : NumberLong(1453893291000),
"duration" : NumberLong(6051000),
"walkingDuration" : NumberLong(6051),
"leg" : [
{
"legId" : "null_null",
"startime" : NumberLong(1453887240000),
"endtime" : NumberLong(1453893291000),
"duration" : NumberLong(6051),
"from" : {
"name" : "parking aisle",
"lon" : "11.140338121521076",
"lat" : "46.06535867118184"
},
"to" : {
"name" : "corner of Via Giuseppe Missori and Via Angelo Butturini",
"lon" : "10.985596",
"lat" : "45.450369"
},
"transport" : {
"type" : "CAR"
},
...
"userId" : "53",
"places" : 4,
"intermediateStops" : false,
"bookings" : [
{
"traveller" : {
"_id" : "52"
},
"recurrent" : false,
"date" : ISODate("2016-01-27T09:34:00.000Z"),
"accepted" : 0
}
],
"active" : true,
"communityIds" : [
"cPCommunity1",
"cPCommunity2"
]
}
```
