### ISSUE TITLE
Communities data missing

### ISSUE THREAD

**Issue by oskarnrk** [smartcommunitylab/sco.carpooling#4]
We need some fields on "getCommunity" response:
- cars (number): number of cars available on the community
- color (string): color of the community in HEX format (#000000)
- zone (string): travel zones of the community

**Comment by oskarnrk** [comment]
- The field "users" has to be an array of User objects (not only Ids)
- We need a new API call like "get community travels"

**Comment by nawaz2013** [comment]
Changes pushed with updated specification.
