### ISSUE TITLE
Offerta viaggio

### ISSUE THREAD

**Issue by paolaR** [smartcommunitylab/sco.carpooling#41]
Selezionando una location da mappa mostra le coordinate, e di seguito mi da errore "OPS!Problema" alla pubblicazione del viaggio. Comportamento non frequente. 

![10 09am gen 15 2016](https://cloud.githubusercontent.com/assets/6916472/12349545/c3681506-bb70-11e5-94b8-84c59fb809db.png)

**Comment by oskarnrk** [comment]
Cannot reproduce!
